- name: copyfiles
  hosts: webservers
  become: yes

  tasks:
  - name: copy files from source file on ansible server to destination on target servers
    copy:
      src: index.html
      dest: /var/www/html/index.html