- name: create user
  hosts: web
  become: yes

  tasks:
  - name: create user
    ansible.builtin.user:
        name: siva
        shell: /bin/bash
        password: "{{ 'Welcome@2026' | password_hash( 'sha512' ) }}"
        groups: wheel
        append: yes
        state: present
