- name: install and run nginx,git and apache
  hosts: web
  become: yes

  tasks:
    - name: install nginx,git,apache
      yum:
        name:
          - nginx
          - git
          - httpd
        state: present

    - name: start and enabled nginx,apache
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      
      loop:
        - nginx
        - httpd
