- name: install and run docker
  hosts: local
  connection: localhost
  become: yes

  tasks:
  - name: Install docker
    ansible.buildin.package:
      name: docker
      state: present
  - name: start and run docker
    ansible.buildin.service:
      name: docker
      state: started
      enabled: yes
