- name: install and run nginx
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start and run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
