- name: install and run nginx and apache
  hosts: web
  become: yes

  tasks:
    - name: install nginx and apache
      yum:
        name:
          - nginx
          - httpd
        state: present

    - name: run and enabled nginx and apache
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - httpd