---
- name: Install NFS packages
  hosts: web
  become: yes

  tasks:

    - name: Install NFS packages
      ansible.builtin.package:
        name:
          - nfs-utils
          - rpcbind
        state: present

    - name: Enable and start rpcbind service
      ansible.builtin.service:
        name: rpcbind
        state: started
        enabled: yes

    - name: Enable and start NFS service
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: yes