- name: install and run nginx
  hosts: web
  become: yes

  tasks:
    - name: Install nginx package
      yum:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
