- name: Install RHSM package and Register RHEL server with Red Hat Subscription Manager
  hosts: web
  become: yes

  tasks:
    - name: Install subscription-manager packaages
      ansible.builtin.package:
        name: subscription-manager
        state: present

    - name: Register with RHSM
      redhat_subscription:
        state: present
        username: "your_username"
        password: "your_password"
        auto_attach: true